### ISSUE TITLE
what's the fps?

### ISSUE THREAD

**Issue by innerop** [jeremyolsen/zed_tensorrt_fasterrcnn#1]
Hi,

I've seen an object detection project which claims around 20fps... by @naisy 

What's the FPS for this?

**Comment by jeremyolsen** [comment]
I haven't coded any metrics into the code line so I'm not exactly sure.  However from my initial testing, it performs much the same as the example that you are referring to.  I forked off of that example to get it to work for Jetpack 3.3 and then used that to start with this ZED integration.  The Zed camera doesn't impact the performance.

**Comment by innerop** [comment]
Cool. thank you for the info. I'll try some of the depth estimation approaches with the Zed camera. It would be great if there was a way to do both object detection and depth estimation (where you can tell a person is N feet away versus a car that's 10 feet away) I might have to upgrade to a Xavier for that. Thanks for sharing your work!
